version = 1

exclude_patterns = [
    ".firebase/**",
    "docs/**",
    "*.config.js"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  plugins = ["react"]